[build]
builder = "DOCKERFILE"

[build.buildArgs]

[deploy]
healthcheckPath = "/api/server"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Expose single GPS device protocol for now
[[deploy.exposedPorts]]
port = 5005
protocol = "tcp"

[env]
RAILWAY_STATIC_URL = "/"
NODE_ENV = "production"
JAVA_OPTS = "-Xms512m -Xmx1024m"
CONFIG_USE_ENVIRONMENT_VARIABLES = "true" 