[build]
builder = "DOCKERFILE"

[build.buildArgs]

[deploy]
healthcheckPath = "/api/server"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Expose multiple ports for GPS device protocols
[[deploy.exposedPorts]]
port = 5001
protocol = "tcp"

[[deploy.exposedPorts]]
port = 5002
protocol = "tcp"

[[deploy.exposedPorts]]
port = 5004
protocol = "tcp"

[[deploy.exposedPorts]]
port = 5005
protocol = "tcp"

[[deploy.exposedPorts]]
port = 5009
protocol = "tcp"

[[deploy.exposedPorts]]
port = 5013
protocol = "tcp"

[[deploy.exposedPorts]]
port = 5014
protocol = "tcp"

[[deploy.exposedPorts]]
port = 5023
protocol = "tcp"

[[deploy.exposedPorts]]
port = 5027
protocol = "tcp"

[[deploy.exposedPorts]]
port = 5055
protocol = "tcp"

[env]
RAILWAY_STATIC_URL = "/"
NODE_ENV = "production"
JAVA_OPTS = "-Xms512m -Xmx1024m"
CONFIG_USE_ENVIRONMENT_VARIABLES = "true" 