name: Build from Frontend Update

on:
  repository_dispatch:
    types: [frontend-updated]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      # Optional: fetch the branch or tag from the payload
      - name: Check the event payload
        run: |
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "SHA: ${{ github.event.client_payload.sha }}"

      # Build your backend and submodule
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew build --no-daemon --stacktrace

      # (Optional) If you want to build the web too, do the Node steps here
      # or you can keep it minimal

      # After build is done, dispatch event to Docker repo
      - name: Dispatch event to Docker
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }} # must allow push/dispatch to enroute-docker
          repository: enroute-logistics/enroute-container
          event-type: backend-built
          client-payload: '{"version":"latest"}'
