name: Build Installers and Dispatch Docker Event

on:
  repository_dispatch:
    types: [frontend-updated]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1.1) Checkout with submodules
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      # 1.2) Update the submodule to the latest commit
      - run: git submodule update --remote --checkout enroute-app

      # 2) Checkout the correct ref for the enroute-app submodule
      - run: git checkout ${{ github.ref_name }}
        working-directory: ./enroute-app

      # 3) Build Java backend
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - run: ./gradlew build

      # 4) Build Web (NPM)
      - uses: actions/setup-node@v4
        with:
          node-version: 18.20.4
          cache: npm
          cache-dependency-path: enroute-app/package-lock.json
      - run: npm install && npm run build
        working-directory: ./enroute-app

      # 5) Build installers (optional, as you have them for distribution)
      - run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install libgcc-s1:i386 libstdc++6:i386
          sudo apt-get install innoextract makeself wine32 s3cmd

      - name: Build installers
        working-directory: ./setup
        run: |
          wget -q http://files.jrsoftware.org/is/5/isetup-5.5.6.exe
          wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4+7/OpenJDK21U-jdk_x64_windows_hotspot_21.0.4_7.zip
          wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4+7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.4_7.tar.gz
          wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4+7/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.4_7.tar.gz
          ./package.sh preview

      # 6) Upload installers to S3
      - name: Upload installers
        working-directory: ./setup
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: s3cmd --acl-public --access_key="$S3_ACCESS_KEY" --secret_key="$S3_SECRET_KEY" put traccar-*.zip s3://$S3_BUCKET/builds/

      # 7) Dispatch event to Docker repo
      # After build is deployed, dispatch event to Docker repo
      - name: Dispatch event to Docker
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }} # must allow push/dispatch to enroute-docker
          repository: enroute-logistics/enroute-container-admin
          event-type: backend-built
          client-payload: '{"version":"latest"}'
